# Generated by Django 3.0.10 on 2020-10-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('state', models.TextField()),
                ('province', models.TextField()),
                ('name', models.TextField()),
                ('type1', models.TextField()),
                ('type2', models.TextField()),
                ('type3', models.TextField()),
                ('rank', models.FloatField()),
                ('search_count', models.FloatField()),
                ('link', models.TextField()),
            ],
        ),
    ]
